server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: false
  datasource:
    url: "jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:taxi_db}"
    username: ${DATABASE_USERNAME:adminapp}
    password: ${DATABASE_PASSWORD:adminapp}
vaadin:
  compatibilityMode: true
logging:
  level:
    org.atmosphere: warn
    spring.boot: info
    ru.taxi.adminpanel: info
    vaadin: info

generator:
  host: ${GENERATOR_HOST_URL:http://localhost:8081}

