server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: "jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:taxi_db}"
    username: ${DATABASE_USERNAME:adminapp}
    password: ${DATABASE_PASSWORD:adminapp}
vaadin:
  compatibilityMode: false
logging:
  level:
    org.atmosphere: warn
    spring.boot: debug
    ru.taxi.adminpanel: debug
    vaadin: debug

generator:
  trips: ${TRIPS_COUNT:10}
  addr: ${ADDRESSES_COUNT:10}
