server:
  port: 8080
spring:
  datasource:
    url: "jdbc:postgresql://${DATABASE_HOST:ec2-54-85-13-135.compute-1.amazonaws.com}:${DATABASE_PORT:5432}/${DATABASE_NAME:d1r2mbfguo9ovh}"
    username: ${DATABASE_USERNAME:ahzyowifzdmqlg}
    password: ${DATABASE_PASSWORD:c2e0694512cbb19009959367b41a91f4043459bd2a18037c187994486aa66084}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
vaadin:
  compatibilityMode: false
logging:
  level:
    org.atmosphere: warn
    spring.boot: ${LOG_LEVEL:info}
    ru.taxi.adminpanel: ${LOG_LEVEL:info}
    vaadin: ${LOG_LEVEL_VAADIN:info}
generator:
  host: ${GENERATOR_HOST_URL:http://localhost:8081}