server:
  port: 8081
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: "jdbc:postgresql://${DATABASE_HOST:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:taxi_db}"
    username: ${DATABASE_USERNAME:adminapp}
    password: ${DATABASE_PASSWORD:adminapp}
vaadin:
  compatibilityMode: false
logging:
  level:
    org.atmosphere: warn
    spring.boot: info
    ru.taxi.adminpanel: info
    vaadin: info

generator:
  trips: ${TRIPS_COUNT:10}
  addr: ${ADDRESSES_COUNT:10}
google-api:
  key: AIzaSyB8V8hR1JKIG9L8ojccE5cOfMD4hS3seoA
  response:
    lang: ru
    sensor: false

