server:
  port: ${PORT:33500}
spring:
  jpa:
    hibernate:
      ddl-auto: create
  datasource:
    url: "jdbc:postgresql://${DATABASE_HOST:ec2-54-85-13-135.compute-1.amazonaws.com}:${DATABASE_PORT:5432}/${DATABASE_NAME:d1r2mbfguo9ovh}"
    username: ${DATABASE_USERNAME:ahzyowifzdmqlg}
    password: ${DATABASE_PASSWORD:c2e0694512cbb19009959367b41a91f4043459bd2a18037c187994486aa66084}
